apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-var
  labels:
    name: nfs-var # name can be anything
spec:
  storageClassName: manual-var # same storage class as pvc
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.200.23
    path: "/vol_containers/var"
