apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-www
  labels:
    name: nfs-www # name can be anything
spec:
  storageClassName: manual-www # same storage class as pvc
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.200.23
    path: "/vol_containers/www"
