apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-5g-db
  labels:
    type: local
spec:
  storageClassName: generic
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /mnt/pv/db
