apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-10g-db
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /mnt/pv/var
