apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-joomla
  labels:
    name: nfs-joomla # name can be anything
spec:
  storageClassName: manual-joomla # same storage class as pvc
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.200.23
    path: "/vol_containers/joomla"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: joomla-data-disk
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual-joomla
  resources:
    requests:
      storage: 2Gi

